/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "theme-base": {
          100: "var(--color-base-100)",
          200: "var(--color-base-200)",
          300: "var(--color-base-300)",
          400: "var(--color-base-400)",
          500: "var(--color-base-500)",
          600: "var(--color-base-600)",
          700: "var(--color-base-700)",
          800: "var(--color-base-800)",
          900: "var(--color-base-900)",
          DEFAULT: "var(--color-base-500)",
          content: "var(--color-base-content)",
        },
        "theme-brand": {
          100: "var(--color-brand-100)",
          200: "var(--color-brand-200)",
          300: "var(--color-brand-300)",
          400: "var(--color-brand-400)",
          500: "var(--color-brand-500)",
          600: "var(--color-brand-600)",
          700: "var(--color-brand-700)",
          800: "var(--color-brand-800)",
          900: "var(--color-brand-900)",
          DEFAULT: "var(--color-brand-500)",
          content: "var(--color-brand-content)",
        },
        "theme-primary": {
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          DEFAULT: "var(--color-primary-500)",
          content: "var(--color-primary-content)",
        },
        "theme-secondary": {
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          DEFAULT: "var(--color-secondary-500)",
          content: "var(--color-secondary-content)",
        },
        "theme-accent": {
          100: "var(--color-accent-100)",
          200: "var(--color-accent-200)",
          300: "var(--color-accent-300)",
          400: "var(--color-accent-400)",
          500: "var(--color-accent-500)",
          600: "var(--color-accent-600)",
          700: "var(--color-accent-700)",
          800: "var(--color-accent-800)",
          900: "var(--color-accent-900)",
          DEFAULT: "var(--color-accent-500)",
          content: "var(--color-accent-content)",
        },
        "theme-neutral": {
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          DEFAULT: "var(--color-neutral-500)",
          content: "var(--color-neutral-content)",
        },
        "theme-info": {
          300: "var(--color-info-300)",
          500: "var(--color-info-500)",
          700: "var(--color-info-700)",
          DEFAULT: "var(--color-info-500)",
          content: "var(--color-info-content)",
        },
        "theme-success": {
          300: "var(--color-success-300)",
          500: "var(--color-success-500)",
          700: "var(--color-success-700)",
          DEFAULT: "var(--color-success-500)",
          content: "var(--color-success-content)",
        },
        "theme-warning": {
          300: "var(--color-warning-300)",
          500: "var(--color-warning-500)",
          700: "var(--color-warning-700)",
          DEFAULT: "var(--color-warning-500)",
          content: "var(--color-warning-content)",
        },
        "theme-error": {
          300: "var(--color-error-300)",
          500: "var(--color-error-500)",
          700: "var(--color-error-700)",
          DEFAULT: "var(--color-error-500)",
          content: "var(--color-error-content)",
        },
      },
    },
  },
  plugins: [],
};
